version: "3.6"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: todos
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/todos
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
volumes:
  db_data:
